//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
// @ts-nocheck

// ISO 8601 date string pattern for JSON reviver
const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?$/;

/**
 * JSON parse reviver that converts ISO date strings to Date objects.
 * This is needed because when using interface-based types (after NSwag migration),
 * dates are not automatically converted from strings to Date objects.
 */
function dateReviver(key: string, value: unknown): unknown {
  if (typeof value === "string" && ISO_DATE_PATTERN.test(value)) {
    const date = new Date(value);
    // Only return Date if it's valid
    if (!isNaN(date.getTime())) {
      return date;
    }
  }
  return value;
}

export class AuthApiBase {
  authToken = "";

  /**
   * JSON parse reviver for converting date strings to Date objects.
   * Subclasses use this when parsing API responses.
   * The dateReviver function is defined in File.Header.liquid template.
   */
  protected jsonParseReviver = dateReviver;

  protected constructor() {}

  // Enforce always return empty string as baseUrl
  getBaseUrl(defaultUrl: string, baseUrl: string) {
    return "";
  }

  setAuthToken(token: string) {
    this.authToken = token;
  }

  protected transformOptions(options: any): Promise<any> {
    if (this.authToken) {
      options.headers["authorization"] = `Bearer ${this.authToken}`;
    }
    return Promise.resolve(options);
  }
}

export class VcmpRegistrationRequestClient extends AuthApiBase {
  private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
  private baseUrl: string;

  constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
    super();
    this.http = http ? http : (window as any);
    this.baseUrl = this.getBaseUrl("", baseUrl);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  search(body?: SearchRegistrationRequestQuery | undefined): Promise<SearchRegistrationRequestResult> {
    let url_ = this.baseUrl + "/api/vcmp/registrationrequest/search";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processSearch(_response);
      });
  }

  protected processSearch(response: Response): Promise<SearchRegistrationRequestResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(_responseText, this.jsonParseReviver) as SearchRegistrationRequestResult);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<SearchRegistrationRequestResult>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  validateRegistrationRequest(body?: ValidateRegistrationRequestQuery | undefined): Promise<ValidationFailure[]> {
    let url_ = this.baseUrl + "/api/vcmp/registrationrequest/validate";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processValidateRegistrationRequest(_response);
      });
  }

  protected processValidateRegistrationRequest(response: Response): Promise<ValidationFailure[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as ValidationFailure[]);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<ValidationFailure[]>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  createRegistrationRequest(body?: CreateRegistrationRequestCommand | undefined): Promise<RegistrationRequest> {
    let url_ = this.baseUrl + "/api/vcmp/registrationrequest/new";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processCreateRegistrationRequest(_response);
      });
  }

  protected processCreateRegistrationRequest(response: Response): Promise<RegistrationRequest> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as RegistrationRequest);
        return result200;
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<RegistrationRequest>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  updateRegistrationRequest(body?: UpdateRegistrationRequestCommand | undefined): Promise<RegistrationRequest> {
    let url_ = this.baseUrl + "/api/vcmp/registrationrequest/update";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: RequestInit = {
      body: content_,
      method: "POST",
      headers: {
        "Content-Type": "application/json-patch+json",
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processUpdateRegistrationRequest(_response);
      });
  }

  protected processUpdateRegistrationRequest(response: Response): Promise<RegistrationRequest> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === "" ? null : (JSON.parse(_responseText, this.jsonParseReviver) as RegistrationRequest);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<RegistrationRequest>(null as any);
  }

  /**
   * @return OK
   */
  getSettings(): Promise<RegistrationRequestSettings> {
    let url_ = this.baseUrl + "/api/vcmp/registrationrequest/settings";
    url_ = url_.replace(/[?&]$/, "");

    let options_: RequestInit = {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.http.fetch(url_, transformedOptions_);
      })
      .then((_response: Response) => {
        return this.processGetSettings(_response);
      });
  }

  protected processGetSettings(response: Response): Promise<RegistrationRequestSettings> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && response.headers.forEach) {
      response.headers.forEach((v: any, k: any) => (_headers[k] = v));
    }
    if (status === 200) {
      return response.text().then((_responseText) => {
        let result200: any = null;
        result200 =
          _responseText === ""
            ? null
            : (JSON.parse(_responseText, this.jsonParseReviver) as RegistrationRequestSettings);
        return result200;
      });
    } else if (status === 401) {
      return response.text().then((_responseText) => {
        return throwException("Unauthorized", status, _responseText, _headers);
      });
    } else if (status === 403) {
      return response.text().then((_responseText) => {
        return throwException("Forbidden", status, _responseText, _headers);
      });
    } else if (status !== 200 && status !== 204) {
      return response.text().then((_responseText) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      });
    }
    return Promise.resolve<RegistrationRequestSettings>(null as any);
  }
}

export interface CreateRegistrationRequestCommand {
  firstName: string;
  lastName: string;
  organizationName: string;
  contactEmail: string;
  contactPhone?: string | undefined;
}

export interface DynamicObjectProperty {
  objectId?: string | undefined;
  values?: DynamicPropertyObjectValue[] | undefined;
  name?: string | undefined;
  description?: string | undefined;
  objectType?: string | undefined;
  isArray?: boolean;
  isDictionary?: boolean;
  isMultilingual?: boolean;
  isRequired?: boolean;
  displayOrder?: number | undefined;
  valueType?: DynamicPropertyValueType;
  displayNames?: DynamicPropertyName[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface DynamicPropertyName {
  locale?: string | undefined;
  name?: string | undefined;
}

export interface DynamicPropertyObjectValue {
  objectType?: string | undefined;
  objectId?: string | undefined;
  locale?: string | undefined;
  value?: any | undefined;
  valueId?: string | undefined;
  valueType?: DynamicPropertyValueType;
  propertyId?: string | undefined;
  propertyName?: string | undefined;
}

export enum DynamicPropertyValueType {
  Undefined = "Undefined",
  ShortText = "ShortText",
  LongText = "LongText",
  Integer = "Integer",
  Decimal = "Decimal",
  DateTime = "DateTime",
  Boolean = "Boolean",
  Html = "Html",
  Image = "Image",
}

export interface RegistrationRequest {
  firstName?: string | undefined;
  lastName?: string | undefined;
  organizationName?: string | undefined;
  contactEmail?: string | undefined;
  contactPhone?: string | undefined;
  status?: string | undefined;
  declineReason?: string | undefined;
  objectType?: string | undefined;
  dynamicProperties?: DynamicObjectProperty[] | undefined;
  createdDate?: Date;
  modifiedDate?: Date | undefined;
  createdBy?: string | undefined;
  modifiedBy?: string | undefined;
  id?: string | undefined;
}

export interface RegistrationRequestSettings {
  registrationFormUrl?: string | undefined;
}

export interface SearchRegistrationRequestQuery {
  contactEmail?: string | undefined;
  statuses?: string[] | undefined;
  responseGroup?: string | undefined;
  objectType?: string | undefined;
  objectTypes?: string[] | undefined;
  objectIds?: string[] | undefined;
  keyword?: string | undefined;
  searchPhrase?: string | undefined;
  languageCode?: string | undefined;
  sort?: string | undefined;
  readonly sortInfos?: SortInfo[] | undefined;
  skip?: number;
  take?: number;
}

export interface SearchRegistrationRequestResult {
  totalCount?: number;
  results?: RegistrationRequest[] | undefined;
}

export enum Severity {
  Error = "Error",
  Warning = "Warning",
  Info = "Info",
}

export enum SortDirection {
  Ascending = "Ascending",
  Descending = "Descending",
}

export interface SortInfo {
  sortColumn?: string | undefined;
  sortDirection?: SortDirection;
}

export interface UpdateRegistrationRequestCommand {
  id: string;
  comment?: string | undefined;
}

export interface ValidateRegistrationRequestQuery {
  registrationRequest?: RegistrationRequest | undefined;
}

export interface ValidationFailure {
  propertyName?: string | undefined;
  errorMessage?: string | undefined;
  attemptedValue?: any | undefined;
  customState?: any | undefined;
  severity?: Severity;
  errorCode?: string | undefined;
  formattedMessagePlaceholderValues?: { [key: string]: any } | undefined;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(message: string, status: number, response: string, headers: { [key: string]: any }, result: any) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new ApiException(message, status, response, headers, null);
}

/* eslint-disable */
